name: Deploy Subfolders to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Deploy fivethexercise
      - name: Deploy fivethexercise
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./fivethexercise

      # 3. Deploy sixthexercise
      - name: Deploy sixthexercise
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./sixthexercise

      # 4. Deploy seventhexrecise
      - name: Deploy seventhexrecise
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./seventhexrecise
